base_path: "/"
brand_title: "へのへのんのの"

styles:
  - "public/style.css"


menu:
  - label: "Links"
    url: "/link"
  - label: "Games"
    url: "/game"
  - label: "Works"
    url: "/work"
  - label: ""
    url: "https://x.com/henohenon_8282"
    icon: "public/x-logo/logo.svg"
  - label: ""
    url: "https://github.com/henohenon"
    icon: "public/github-mark/github-mark-white.svg"